### PR TITLE
Revert "delete build files since most people minify their own build a…

### PR DESCRIPTION
**Pull request by Timgur**
We can't delete the build because it needs to be ran through babel compiler to run out of the box

### CODE REVIEW

**Comment by ecto** [comment]
i think we should, and distribute a compiled version separately. there is no reason to have the build in this repo

**Comment by Timgur** [comment]
That is a good idea. I just didnt want  it to be broken on MW deving for
now.

**Comment by pastudan** [comment]
agreed with @ecto .. github even lets you publish tars / zips / binaries. that's where the code that runs out of the box should go.

**Comment by andytuba** [comment]
^ use /releases for that

**Pull request merged**
